# fly.toml app configuration file generated for jakshim-backend on 2023-07-26T21:11:20+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "jakshim-backend"
primary_region = "nrt"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
